esphome:
  name: esp32-powermeter
  friendly_name: esp32-powermeter

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  baud_rate: 0
# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    static_ip: 
    gateway: 
    subnet: 
    dns1: 
    dns2: 
    
  power_save_mode: NONE

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Powermeter"
    password: ""

captive_portal:

uart:
  - id: ubus1
    tx_pin: GPIO1
    rx_pin: GPIO3
    baud_rate: 9600
    stop_bits: 2     #For ESP32 try value 2

time:
  - platform: homeassistant
    id: homeassistant_time

#### PZEM-004T V3 ####
sensor:
  - platform: pzemac
    id: pzemac_1
    address: 1
    current:
      name: "p_current"
      id: p_current
      accuracy_decimals: 2
    voltage:
      name: "p_voltage"
      id: p_voltage
      accuracy_decimals: 2
    power:
      name: "p_watt"
      id: p_watt
      unit_of_measurement: W
      accuracy_decimals: 2
    frequency:
      name: "p_frequency"
      id: p_frequency
      unit_of_measurement: Hz
      accuracy_decimals: 2
    power_factor:
      name: "p_power_factory"
      id: p_power_factory
      accuracy_decimals: 2
    energy:
      name: "p_energy"
      id: p_energy
      unit_of_measurement: Kwh
      filters:
        - multiply: 0.001
      accuracy_decimals: 4
    update_interval: 5s

  - platform: total_daily_energy
    name: "Total Daily Energy"
    unit_of_measurement: kWh
    accuracy_decimals: 4
    power_id: p_energy
    id: total_dialy_energy

  - platform: template
    name: "Electricity Cost (Day)"
    unit_of_measurement: "THB"
    accuracy_decimals: 2
    lambda: |-
      return id(p_energy).state * 4.70;
    update_interval: 5s
  
  - platform: template
    name: "Electricity Cost (Total)"
    unit_of_measurement: "THB"
    accuracy_decimals: 2
    lambda: |-
      return id(total_dialy_energy).state * 4.70;
    update_interval: 5s

  - platform: template
    name: "Total Monthly Energy"
    unit_of_measurement: kWh
    accuracy_decimals: 4
    id: total_monthly_energy
    lambda: |-
      static float last_month_energy = 0;
      static int last_month = -1;
      int current_month = id(homeassistant_time).now().month;
      if (last_month != current_month) {
        last_month_energy = 0;
      }
      last_month = current_month;
      return last_month_energy += id(p_energy).state;

  - platform: template
    name: "Total Yearly Energy"
    unit_of_measurement: kWh
    accuracy_decimals: 4
    id: total_yearly_energy
    lambda: |-
      static float last_year_energy = 0;
      static int last_year = -1;
      int current_year = id(homeassistant_time).now().year;
      if (last_year != current_year) {
        last_year_energy = 0;
      }
      last_year = current_year;
      return last_year_energy += id(p_energy).state;

  - platform: template
    name: "Electricity Cost (Monthly)"
    unit_of_measurement: "THB"
    accuracy_decimals: 2
    lambda: |-
      return id(total_monthly_energy).state * 4.70;
    update_interval: 5s

  - platform: template
    name: "Electricity Cost (Yearly)"
    unit_of_measurement: "THB"
    accuracy_decimals: 2
    lambda: |-
      return id(total_yearly_energy).state * 4.70;
    update_interval: 5s

  - platform: wifi_signal
    name: "WiFi power_pMeter"
    update_interval: 60s
    
  - platform: uptime
    name: "up"
    id: uptime_sec

binary_sensor:
  - platform: status
    name: "pMeter_status"    
      
text_sensor:
  - platform: template
    name: pMeter_uptime
    lambda: |-
      int seconds = (id(uptime_sec).state);
      int days = seconds / (24 * 3600);
      seconds = seconds % (24 * 3600); 
      int hours = seconds / 3600;
      seconds = seconds % 3600;
      int minutes = seconds /  60;
      seconds = seconds % 60;
      return { (String(days) +"d " + String(hours) +"h " + String(minutes) +"m "+ String(seconds) +"s").c_str() };
    icon: mdi:clock-start
    update_interval: 60s

switch:
  - platform: restart
    name: "EMeter_restart"
    
  - platform: uart
    name: "EMeter Reset Energy"
    data: [0x01, 0x42, 0x80, 0x11]

http_request:
  useragent: esphome/device
  timeout: 10s
  verify_ssl: false

button:
  - platform: template
    name: "Reset Energy"
    on_press:
      - pzemac.reset_energy: pzemac_1
  
  - platform: template
    name: "Send Telegram message"
    on_press:
      - http_request.post:
          url: ""
          headers:
            Content-Type: application/json
          json:
            chat_id: ""
            text: !lambda |
              #include <time.h>
              time_t now_time;
              ::time(&now_time); // ใช้ :: เพื่อระบุ namespace global
              struct tm *time_info;
              time_info = localtime(&now_time);

              char buffer[256]; // ปรับขนาด buffer ตามต้องการ
              sprintf(buffer, 
                "Power Meter Status:\n"
                "  Date: %02d/%02d/%04d\n"
                "  Time: %02d:%02d:%02d\n"
                "  Volt: %.2f V\n"
                "  Amp:  %.2f A\n"
                "  Watt: %.2f W\n"
                "  Freq: %.2f Hz\n"
                "  KWh:  %.4f KWh\n"
                "  PF:   %.2f\n"
                "  Cost (Today): %.2f THB",
                time_info->tm_mday, time_info->tm_mon + 1, time_info->tm_year + 1900,
                time_info->tm_hour, time_info->tm_min, time_info->tm_sec,
                id(p_voltage).state, id(p_current).state, id(p_watt).state,
                id(p_frequency).state, id(p_energy).state, id(p_power_factory).state,
                id(p_energy).state * 4.70
              );
              return buffer;

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true

display:
  - platform: lcd_pcf8574
    dimensions: 
      - 20
      - 4
    address: 0x27
    update_interval: 5s
    lambda: |-

      // Print Power (W) and Current (A)
      it.printf(0, 0, "Volt:%.2f", id(p_voltage).state);
      it.printf(12, 0, "Amp:%.2f", id(p_current).state);

      // Print Voltage (V) and Frequency (Hz)
      it.printf(0, 1, "Watt:%.2f", id(p_watt).state);
      it.printf(12, 1, "Hz:%.12f", id(p_frequency).state);

      // Print Voltage (V) and Frequency (Hz)
      it.printf(0, 2, "Kwh:%.4f", id(p_energy).state);
      it.printf(12, 2, "PF:%.2f", id(p_power_factory).state);

      // Print Time (HH:MM format)
      it.printf(0, 3, "THB:%.2f", (id(p_energy).state)*4.70);
      it.strftime(12, 3, "T:%H:%M", id(homeassistant_time).now());
